apiVersion: v1
kind: Secret
metadata:
    name: pixabay-apikey
data:
    API_KEY: ENC[AES256_GCM,data:dLxiGNxcHhOVg9rhz6eHft/voyxq31ZsxTfocrv9SqlP7VhOREEUivFQID1Fnw4T+0J52xB3k1A=,iv:ahwK4CGcW9tDY+FaCHDXWzCYPMnaIxq6fhlGiUJOPNw=,tag:7FJpt+QOGamWIfklKJmTzQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17mgq9ygh23q0cr00mjn0dfn8msak0apdy0ymjv5k50qzy75zmfkqzjdam4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhMG9lZE9Ua0xzMis1M0pK
            WXFkeE1qYkxnUzZ5V3psMm1VREpSUzZVMFVvCnh4MnZsQ25NMVZObmF3cVBMdDkr
            TUNoTXNIcW1wYXdlNFVWbURiYnhXaU0KLS0tIGgrbnFGSEpTc0hFZlI2U1NNZVhH
            TFkweFFhL1ZoOW5aUmFHRDA1THFoMFEKH4HCoJQke32jvaWdbAUoIJlBKt7yE2W8
            KABk3N4jAVjYCp2xXGXWnCL48dlYPTcDjKjsN99nnyKUVIUruJ0prg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14wju253ucca88q03cl4f00tcckhcsalwh9sn7svpkhw2r6estc4q7utfqh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bEd2YnVObWsxb0d6TEgw
            bjBZSmJ0MStKRGIweFprNlowN0RObHVkNms0Cm94WU1nU1NRQXJTNDFnWHJ2UVgw
            NTFsU1ZieXpreXFIejJnM2tzNzk2a2MKLS0tIEdoank5cURzSGVxeSthT1lFMjVL
            NXIrSVQyV3d1UVF2aGtkdHJmWmJ1c3cKQDDdiqkX2xwcl7gVenaMzvhT87uD2e4I
            wo/SJ9xydTdbpNazm4k88wuGmOm7opzgnJRNb+Uh1DyPky5HqUt+CA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-10-29T13:11:44Z"
    mac: ENC[AES256_GCM,data:g8pKyC4Ao9QNFa/xip29xRjAiNl7pVq0boELGBUAdJNjQvx2pF8LeQzJhP/kaNUKqlnKru3f+XAFDfQgkLqauHxiuxTtnJ1Z5BfIBs/fHP5sqoRgTwEOKc+npSpW/T50TNp1SiHnMEDQowAuVtB4gfh5V3J12+8aKFTvz/j0UtA=,iv:XffYRGUR/IkxXLM/e8PGTwa+wSTBZT6ps3di9rBSdQw=,tag:63WXjEa5nrqYqo3xd1Hcug==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.1
