# permissions for end users to edit countdowns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: countdown-editor-role
rules:
- apiGroups:
  - stable.dwk.stable.dwk
  resources:
  - countdowns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stable.dwk.stable.dwk
  resources:
  - countdowns/status
  verbs:
  - get
