# permissions for end users to view countdowns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: countdown-viewer-role
rules:
- apiGroups:
  - stable.dwk.stable.dwk
  resources:
  - countdowns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - stable.dwk.stable.dwk
  resources:
  - countdowns/status
  verbs:
  - get
