apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashgenerator-dep
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashgenerator
  template:
    metadata:
      labels:
        app: hashgenerator
    spec:
      containers:
        - name: hashgenerator
          image: IMAGE_PLACEHOLDER
