apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: jakousa/dwk-4-gitops-app
  newTag: 5e7dbe06e256b14260dbb5ba74dc045f5e96493f
