name: Release app3 image response

on:
  push:
    branches: 
      - master
    paths:
      - 'app3/image-response/**'
      - '.github/workflows/app3-image-response.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=jakousa/dwk-app3-image-response
          # Set the platforms to build for here and thus reduce duplicating it.
          PLATFORMS=amd64,arm,arm64
          TAGS="${DOCKER_IMAGE}:${{ github.sha }}"

          # Set output parameters.

          if [ "${{github.event_name}}" == "pull_request" ]; then
            echo ::set-output name=push::false
          else
            echo ::set-output name=push::true
            echo ::set-output name=tags::${TAGS}
            echo ::set-output name=docker_image::${DOCKER_IMAGE}
          fi
          echo ::set-output name=platforms::${PLATFORMS}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: ${{ steps.prep.outputs.platforms }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
          version: latest
          driver-opts: image=moby/buildkit:latest

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: app3/image-response
          platforms: ${{ steps.prep.outputs.platforms }}
          push: ${{ steps.prep.outputs.push }}
          tags: ${{ steps.prep.outputs.tags }}